"""PolarPandas v5 — Code Generator.

Walks the AST produced by ``parser.parse`` (already validated by
``semv.validate``) and emits a single, self-contained Python 3.12 script
that uses ``polars`` for every data-manipulation step and switches to
``pandas`` + ``matplotlib`` only when a ``PLOT`` statement is reached.

Design notes
------------
* The generator is a pure tree-walker: one ``_emit_*`` method per AST
  node kind, all writing into the same internal line buffer.
* ``FOR`` blocks are unrolled at compile time per spec section 6.3.
  Each iteration is materialised as a textual copy of the body in which
  the loop variable is replaced by the current column name.  The
  generated code therefore contains no Python-level ``for`` loop.
* ``IF`` blocks are lowered to a Python ``if/else`` whose guard is built
  from the ``MetaCondition`` tree (``EXISTS df.col``,
  ``ROWCOUNT df > N``, plus ``AND``/``OR``).
* ``READ '<path>'`` introduces a polars dataframe whose variable name is
  derived from the file stem with the same rule the validator uses
  (``_dataset_name_from_path``).  The most recently introduced
  dataframe is the *active* one and is referenced as ``df`` in the
  emitted code via an alias assignment.
* ``PLOT`` materialises ``df.to_pandas()`` once and then dispatches on
  the chart kind.

Public entry point
------------------
``generate(ast: list[ASTNode]) -> str``
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import PurePath
from typing import Optional

from parser import (
    ASTNode,
    AstCast,
    AstDropColumns,
    AstDropDuplicates,
    AstDropEmpty,
    AstFillEmpty,
    AstFilter,
    AstFor,
    AstGroupBy,
    AstIf,
    AstInfo,
    AstKeep,
    AstMerge,
    AstPipeline,
    AstPlot,
    AstPreview,
    AstRead,
    AstRename,
    AstSave,
    AstSet,
    AstSort,
    CondAnd,
    CondBetween,
    CondCompare,
    CondContains,
    CondIn,
    CondNull,
    CondOr,
    Condition,
    Expr,
    ExprBinop,
    ExprColRef,
    ExprLiteral,
    MetaAnd,
    MetaCondition,
    MetaExists,
    MetaOr,
    MetaRowCount,
    OperationNode,
)


# ---------------------------------------------------------------------------
# Public errors
# ---------------------------------------------------------------------------

class CodeGenError(Exception):
    """Raised for situations the validator should already have caught.

    The generator assumes a validated AST; this exception guards against
    misuse rather than user-facing language errors.
    """

    def __init__(self, message: str, line: int = 0) -> None:
        super().__init__(f"[CodeGen] line {line}: {message}")
        self.message = message
        self.line = line


# ---------------------------------------------------------------------------
# Constant translation tables
# ---------------------------------------------------------------------------

_HEADER_LINES: tuple[str, ...] = (
    "# Generated by PolarPandas v5 — DO NOT EDIT",
    "# Regenerate with:  python -m main <source>.pp -o <out>.py",
    "from __future__ import annotations",
    "",
    "import polars as pl",
    "",
)

# Lazily-imported plotting backends.  We add the imports only when a
# program actually contains a PLOT statement, to keep the generated
# script lightweight for non-visual pipelines.
_PLOT_IMPORTS: tuple[str, ...] = (
    "import pandas as pd  # noqa: F401  (used by PLOT)",
    "import matplotlib.pyplot as plt  # noqa: F401  (used by PLOT)",
)

_READ_BY_EXT: dict[str, str] = {
    ".csv":     "pl.read_csv",
    ".parquet": "pl.read_parquet",
    ".json":    "pl.read_json",
    ".xlsx":    "pl.read_excel",
}

_WRITE_BY_EXT: dict[str, str] = {
    ".csv":     "write_csv",
    ".parquet": "write_parquet",
    ".json":    "write_json",
    ".xlsx":    "write_excel",
}

_DTYPE_TO_PL: dict[str, str] = {
    "NUMBER":  "pl.Float64",
    "DECIMAL": "pl.Float64",
    "TEXT":    "pl.Utf8",
    "DATE":    "pl.Date",
    "BOOLEAN": "pl.Boolean",
}

_AGG_METHOD: dict[str, str] = {
    "SUM":     "sum",
    "AVERAGE": "mean",
    "COUNT":   "count",
    "MAX":     "max",
    "MIN":     "min",
}

_FILL_METHOD_TO_PL: dict[str, str] = {
    "mean":   "mean()",
    "median": "median()",
    "mode":   "mode().first()",
    "ffill":  "FORWARD",   # special-cased to fill_null(strategy='forward')
    "bfill":  "BACKWARD",  # special-cased to fill_null(strategy='backward')
}

_HOW_TO_PL: dict[str, str] = {
    "INNER": "inner",
    "LEFT":  "left",
    "RIGHT": "right",
    "OUTER": "outer",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ext(path: str) -> str:
    return PurePath(path).suffix.lower()


def _dataset_name_from_path(path: str) -> str:
    """Same rule as the semantic validator (kept in-sync intentionally)."""
    stem = PurePath(path).stem
    sanitized = re.sub(r"[^A-Za-z0-9_]", "_", stem)
    if not sanitized:
        return "_"
    if sanitized[0].isdigit():
        return f"_{sanitized}"
    return sanitized


def _py_str(s: str) -> str:
    """Render a Python string literal with single quotes, escaping safely."""
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


# ---------------------------------------------------------------------------
# Internal generator state
# ---------------------------------------------------------------------------

@dataclass
class _State:
    lines: list[str] = field(default_factory=list)
    indent: int = 0
    needs_plot_imports: bool = False
    # name of the most recently introduced dataframe variable
    active: Optional[str] = None
    # mapping loop variable name -> concrete column name (current iteration)
    loop_subst: dict[str, str] = field(default_factory=dict)

    def emit(self, line: str = "") -> None:
        self.lines.append(("    " * self.indent) + line if line else "")

    def emit_block(self, lines: list[str]) -> None:
        for ln in lines:
            self.emit(ln)


# ---------------------------------------------------------------------------
# Expression / condition emitters
# ---------------------------------------------------------------------------

def _emit_expr(expr: Expr, st: _State) -> str:
    """Translate an ``Expr`` into a polars expression string."""
    if isinstance(expr, ExprLiteral):
        if expr.kind == "string":
            # parser keeps original quotes; normalise to a python literal
            raw = expr.value
            if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in ("'", '"'):
                raw = raw[1:-1]
            return _py_str(raw)
        if expr.kind == "bool":
            return "True" if expr.value.lower() == "true" else "False"
        # integer or float
        return expr.value

    if isinstance(expr, ExprColRef):
        name = st.loop_subst.get(expr.name, expr.name) if expr.is_loopvar else expr.name
        return f"pl.col({_py_str(name)})"

    if isinstance(expr, ExprBinop):
        left = _emit_expr(expr.left, st)
        right = _emit_expr(expr.right, st)
        return f"({left} {expr.op} {right})"

    raise CodeGenError(f"Unknown expression node {type(expr).__name__}")


def _resolve_col(name: str, is_loopvar: bool, st: _State) -> str:
    """Resolve a possibly-loopvar column name to its concrete name."""
    if is_loopvar and name in st.loop_subst:
        return st.loop_subst[name]
    return name


def _emit_condition(cond: Condition, st: _State) -> str:
    """Translate a filter condition tree into a polars boolean expression."""
    if isinstance(cond, CondCompare):
        return f"({_emit_expr(cond.left, st)} {cond.op} {_emit_expr(cond.right, st)})"

    if isinstance(cond, CondIn):
        col = _emit_expr(cond.col, st)
        values = ", ".join(_emit_expr(v, st) for v in cond.values)
        body = f"{col}.is_in([{values}])"
        return f"(~{body})" if cond.negate else body

    if isinstance(cond, CondNull):
        col = _emit_expr(cond.col, st)
        body = f"{col}.is_null()"
        return f"(~{body})" if cond.is_not else body

    if isinstance(cond, CondBetween):
        col = _emit_expr(cond.col, st)
        lo = _emit_expr(cond.low, st)
        hi = _emit_expr(cond.high, st)
        return f"({col}.is_between({lo}, {hi}))"

    if isinstance(cond, CondContains):
        col = _emit_expr(cond.col, st)
        val = _emit_expr(cond.value, st)
        body = f"{col}.cast(pl.Utf8).str.contains({val}, literal=True)"
        return f"(~{body})" if cond.negate else body

    if isinstance(cond, CondAnd):
        return f"({_emit_condition(cond.left, st)} & {_emit_condition(cond.right, st)})"

    if isinstance(cond, CondOr):
        return f"({_emit_condition(cond.left, st)} | {_emit_condition(cond.right, st)})"

    raise CodeGenError(f"Unknown condition node {type(cond).__name__}")


def _emit_meta_condition(mcond: MetaCondition, st: _State) -> str:
    """Translate an IF guard into a Python boolean expression."""
    if isinstance(mcond, MetaExists):
        # EXISTS <name> — name may be 'df' or 'df.col'.  We support both:
        if "." in mcond.name:
            df, col = mcond.name.split(".", 1)
            return f"({_py_str(col)} in {df}.columns)"
        return f"({mcond.name!r} in globals())"

    if isinstance(mcond, MetaRowCount):
        return f"({mcond.name}.height {mcond.op} {mcond.value})"

    if isinstance(mcond, MetaAnd):
        return f"({_emit_meta_condition(mcond.left, st)} and {_emit_meta_condition(mcond.right, st)})"

    if isinstance(mcond, MetaOr):
        return f"({_emit_meta_condition(mcond.left, st)} or {_emit_meta_condition(mcond.right, st)})"

    raise CodeGenError(f"Unknown meta-condition {type(mcond).__name__}")


# ---------------------------------------------------------------------------
# Operation emitters (each updates `df = ...` for the active dataframe)
# ---------------------------------------------------------------------------

def _emit_save(node: AstSave, st: _State) -> None:
    ext = _ext(node.path)
    writer = _WRITE_BY_EXT.get(ext, "write_csv")
    st.emit(f"df.{writer}({_py_str(node.path)})")


def _emit_preview(node: AstPreview, st: _State) -> None:
    st.emit(f"print(df.head({node.rows}))")


def _emit_info(_: AstInfo, st: _State) -> None:
    st.emit("print(df.schema)")
    st.emit("print(f'rows={df.height}, cols={df.width}')")


def _emit_drop_empty(node: AstDropEmpty, st: _State) -> None:
    if node.columns:
        cols = [st.loop_subst.get(c, c) for c in node.columns]
        col_list = ", ".join(_py_str(c) for c in cols)
        st.emit(f"df = df.drop_nulls(subset=[{col_list}])")
    else:
        st.emit("df = df.drop_nulls()")


def _emit_drop_duplicates(_: AstDropDuplicates, st: _State) -> None:
    st.emit("df = df.unique(keep='first')")


def _emit_drop_columns(node: AstDropColumns, st: _State) -> None:
    cols = [st.loop_subst.get(c, c) for c in node.columns]
    col_list = ", ".join(_py_str(c) for c in cols)
    st.emit(f"df = df.drop([{col_list}])")


def _emit_fill(node: AstFillEmpty, st: _State) -> None:
    col = st.loop_subst.get(node.column, node.column)
    val = node.value
    # Method name? (e.g. mean / median / mode / ffill / bfill)
    if isinstance(val, ExprColRef) and not val.is_loopvar and val.name.lower() in _FILL_METHOD_TO_PL:
        method = _FILL_METHOD_TO_PL[val.name.lower()]
        if method == "FORWARD":
            st.emit(
                f"df = df.with_columns(pl.col({_py_str(col)})"
                f".fill_null(strategy='forward'))"
            )
            return
        if method == "BACKWARD":
            st.emit(
                f"df = df.with_columns(pl.col({_py_str(col)})"
                f".fill_null(strategy='backward'))"
            )
            return
        st.emit(
            f"df = df.with_columns(pl.col({_py_str(col)})"
            f".fill_null(pl.col({_py_str(col)}).{method}))"
        )
        return
    # Literal fallback
    rendered = _emit_expr(val, st)
    st.emit(f"df = df.with_columns(pl.col({_py_str(col)}).fill_null({rendered}))")


def _emit_keep(node: AstKeep, st: _State) -> None:
    cols = [st.loop_subst.get(c, c) for c in node.columns]
    col_list = ", ".join(_py_str(c) for c in cols)
    st.emit(f"df = df.select([{col_list}])")


def _emit_cast(node: AstCast, st: _State) -> None:
    col = st.loop_subst.get(node.column, node.column)
    pl_dtype = _DTYPE_TO_PL[node.dtype]
    strict = "False" if node.on_error == "SKIP" else "True"
    st.emit(
        f"df = df.with_columns(pl.col({_py_str(col)}).cast({pl_dtype}, strict={strict}))"
    )


def _emit_set(node: AstSet, st: _State) -> None:
    col = st.loop_subst.get(node.column, node.column)
    rhs = _emit_expr(node.expr, st)
    st.emit(f"df = df.with_columns(({rhs}).alias({_py_str(col)}))")


def _emit_rename(node: AstRename, st: _State) -> None:
    old = st.loop_subst.get(node.old, node.old)
    new = st.loop_subst.get(node.new, node.new)
    st.emit(f"df = df.rename({{{_py_str(old)}: {_py_str(new)}}})")


def _emit_sort(node: AstSort, st: _State) -> None:
    col = st.loop_subst.get(node.column, node.column)
    desc = "True" if node.direction == "DESC" else "False"
    st.emit(f"df = df.sort({_py_str(col)}, descending={desc})")


def _emit_group_by(node: AstGroupBy, st: _State) -> None:
    by = [st.loop_subst.get(c, c) for c in node.by]
    by_list = ", ".join(_py_str(c) for c in by)
    target = st.loop_subst.get(node.column, node.column)
    method = _AGG_METHOD[node.agg]
    if node.agg == "COUNT":
        # COUNT semantics: count non-null entries of the target column
        agg_expr = f"pl.col({_py_str(target)}).count().alias({_py_str(target)})"
    else:
        agg_expr = f"pl.col({_py_str(target)}).{method}().alias({_py_str(target)})"
    st.emit(f"df = df.group_by([{by_list}]).agg({agg_expr})")


def _emit_merge(node: AstMerge, st: _State) -> None:
    if node.source_is_file:
        # Inline READ for the right-hand side
        ext = _ext(node.source)
        reader = _READ_BY_EXT.get(ext, "pl.read_csv")
        rhs_var = "_rhs"
        if reader == "pl.read_csv":
            st.emit(f"{rhs_var} = {reader}({_py_str(node.source)}, infer_schema_length=None)")
        else:
            st.emit(f"{rhs_var} = {reader}({_py_str(node.source)})")
    else:
        rhs_var = node.source
    how = _HOW_TO_PL[node.how]
    on = st.loop_subst.get(node.on, node.on)
    st.emit(f"df = df.join({rhs_var}, on={_py_str(on)}, how={_py_str(how)})")


def _emit_filter(node: AstFilter, st: _State) -> None:
    cond = _emit_condition(node.condition, st)
    st.emit(f"df = df.filter({cond})")


def _emit_plot(node: AstPlot, st: _State) -> None:
    st.needs_plot_imports = True
    target = node.target if node.target else "df"
    st.emit(f"_pdf = {target}.to_pandas()")
    st.emit("_fig, _ax = plt.subplots()")

    kind = node.kind
    if kind == "hist":
        st.emit(f"_ax.hist(_pdf[{_py_str(node.x)}])")
    elif kind == "box":
        if node.x:
            st.emit(
                f"_pdf.boxplot(column={_py_str(node.y)}, by={_py_str(node.x)}, ax=_ax)"
            )
        else:
            st.emit(f"_ax.boxplot(_pdf[{_py_str(node.y)}].dropna())")
    elif kind == "pie":
        if node.y:
            st.emit(
                f"_ax.pie(_pdf[{_py_str(node.y)}], labels=_pdf[{_py_str(node.x)}])"
            )
        else:
            st.emit(
                f"_ax.pie(_pdf[{_py_str(node.x)}].value_counts(), "
                f"labels=_pdf[{_py_str(node.x)}].value_counts().index)"
            )
    elif kind == "scatter":
        st.emit(f"_ax.scatter(_pdf[{_py_str(node.x)}], _pdf[{_py_str(node.y)}])")
    elif kind == "bar":
        st.emit(f"_ax.bar(_pdf[{_py_str(node.x)}], _pdf[{_py_str(node.y)}])")
    elif kind == "line":
        st.emit(f"_ax.plot(_pdf[{_py_str(node.x)}], _pdf[{_py_str(node.y)}])")
    else:  # pragma: no cover — validator should have rejected this
        raise CodeGenError(f"Unsupported plot kind '{kind}'", node.line)

    if node.x and kind not in ("pie",):
        st.emit(f"_ax.set_xlabel({_py_str(node.x)})")
    if node.y and kind not in ("pie", "hist"):
        st.emit(f"_ax.set_ylabel({_py_str(node.y)})")
    if node.title:
        st.emit(f"_ax.set_title({_py_str(node.title)})")

    if node.save:
        st.emit(f"_fig.savefig({_py_str(node.save)})")
    st.emit("plt.show()")


# ---------------------------------------------------------------------------
# Operation dispatcher
# ---------------------------------------------------------------------------

_OP_DISPATCH = {
    AstSave:           _emit_save,
    AstPreview:        _emit_preview,
    AstInfo:           _emit_info,
    AstDropEmpty:      _emit_drop_empty,
    AstDropDuplicates: _emit_drop_duplicates,
    AstDropColumns:    _emit_drop_columns,
    AstFillEmpty:      _emit_fill,
    AstKeep:           _emit_keep,
    AstCast:           _emit_cast,
    AstSet:            _emit_set,
    AstRename:         _emit_rename,
    AstSort:           _emit_sort,
    AstGroupBy:        _emit_group_by,
    AstMerge:          _emit_merge,
    AstFilter:         _emit_filter,
    AstPlot:           _emit_plot,
}


def _emit_operation(node: OperationNode, st: _State) -> None:
    handler = _OP_DISPATCH.get(type(node))
    if handler is None:
        raise CodeGenError(f"Unknown operation node {type(node).__name__}",
                           getattr(node, "line", 0))
    handler(node, st)


# ---------------------------------------------------------------------------
# Top-level statement emitters
# ---------------------------------------------------------------------------

def _emit_read(node: AstRead, st: _State) -> None:
    ext = _ext(node.path)
    reader = _READ_BY_EXT.get(ext, "pl.read_csv")
    name = _dataset_name_from_path(node.path)
    # For CSV, scan the whole file to pick robust dtypes — avoids the classic
    # "could not parse '1.32' as i64" trap when fractional values appear later
    # in an otherwise integer-looking column.
    if reader == "pl.read_csv":
        st.emit(f"{name} = {reader}({_py_str(node.path)}, infer_schema_length=None)")
    else:
        st.emit(f"{name} = {reader}({_py_str(node.path)})")
    st.emit(f"df = {name}")
    st.active = name


def _emit_pipeline(node: AstPipeline, st: _State) -> None:
    if node.target is not None:
        st.emit(f"df = {node.target}")
        st.active = node.target
    for step in node.steps:
        _emit_operation(step, st)
    # Re-bind the named dataframe so later pipelines on the same name
    # observe the mutation (mirrors most users' mental model).
    if st.active:
        st.emit(f"{st.active} = df")


def _emit_if(node: AstIf, st: _State) -> None:
    guard = _emit_meta_condition(node.condition, st)
    st.emit(f"if {guard}:")
    st.indent += 1
    if node.then_body:
        for child in node.then_body:
            _emit_statement(child, st)
    else:
        st.emit("pass")
    st.indent -= 1
    if node.else_body:
        st.emit("else:")
        st.indent += 1
        for child in node.else_body:
            _emit_statement(child, st)
        st.indent -= 1


def _emit_for(node: AstFor, st: _State) -> None:
    """Compile-time unrolling of the FOR body."""
    st.emit(f"# unrolled FOR ${node.var} IN {', '.join(node.columns)}")
    for col in node.columns:
        st.loop_subst[node.var] = col
        st.emit(f"# -- iteration: ${node.var} = {col}")
        for child in node.body:
            _emit_statement(child, st)
        st.loop_subst.pop(node.var, None)


def _emit_statement(node: ASTNode, st: _State) -> None:
    if isinstance(node, AstRead):
        _emit_read(node, st)
        return
    if isinstance(node, AstPipeline):
        _emit_pipeline(node, st)
        return
    if isinstance(node, AstIf):
        _emit_if(node, st)
        return
    if isinstance(node, AstFor):
        _emit_for(node, st)
        return
    # All remaining ASTNodes are also OperationNodes used standalone.
    _emit_operation(node, st)  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def generate(ast: list[ASTNode]) -> str:
    """Translate a validated AST into a runnable Python source string."""
    st = _State()
    for node in ast:
        _emit_statement(node, st)

    header = list(_HEADER_LINES)
    if st.needs_plot_imports:
        header.extend(_PLOT_IMPORTS)
        header.append("")
    return "\n".join(header + st.lines) + "\n"